# cloudbuild.yaml
steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
    - gcloud
    - functions
    - deploy
    - imginfo-checkimg
    - --source=.
    - --runtime=python311
    - --trigger-http
    - --allow-unauthenticated
    - --entry-point=checkimg
    - --region=asia-northeast1
    - --set-env-vars=GCS_BUCKET_NAME=checkimg
# 以下を追加
options:
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET