# cloudbuild.yaml
steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
    - gcloud
    - functions
    - deploy
    - model_generate_v2
    - --source=.
    - --runtime=python311
    - --trigger-http
    - --allow-unauthenticated
    - --entry-point=model_generate_v2
    - --region=asia-northeast1
    - --set-env-vars=GCS_BUCKET_NAME=gcf-v2-uploads-350672083698.asia-northeast1.cloudfunctions.appspot.com # ★ここに正しいバケット名を設定！
# 以下を追加
options:
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET