# cloudbuild.yaml
steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
    - gcloud
    - functions
    - deploy
    - model-generate-v2
    - --source=.
    - --runtime=python311
    - --trigger-http
    - --allow-unauthenticated
    - --entry-point=main
    - --region=asia-northeast1

# 以下を追加
options:
  # REGIONAL_USER_OWNED_BUCKET: リージョンにユーザーが所有するバケットを使用する
  # これは、ビルドのログとアーティファクトを保存するバケットの場所と所有権を制御します。
  # このオプションを設定しないと、ビルドがデフォルトのログバケットを見つけられない場合にエラーになることがあります。
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET